# Generated by Django 2.0.6 on 2018-06-25 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0002_auto_20180624_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassifiedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('classifier_algorithm', models.CharField(choices=[('white-black', 'simple white black algorithm'), ('svn', 'svn ML')], max_length=50)),
                ('is_floor_plan', models.FloatField()),
            ],
            options={
                'ordering': ('classified_at',),
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterModelOptions(
            name='imagerecord',
            options={'ordering': ('uploaded_at',)},
        ),
        migrations.RenameField(
            model_name='imagerecord',
            old_name='created',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AddField(
            model_name='classifiedimage',
            name='image_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor_plans.ImageRecord'),
        ),
    ]
