# Generated by Django 2.0.6 on 2018-06-25 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0003_auto_20180625_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedimage',
            name='image_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifiers', to='floor_plans.ImageRecord'),
        ),
    ]
