# Generated by Django 2.0.6 on 2018-06-26 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0004_auto_20180626_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedimage',
            name='image_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='floor_plans.ImageRecord'),
        ),
    ]
