# Generated by Django 2.0.6 on 2018-06-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0005_auto_20180626_1617'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classifiedimage',
            old_name='image_record',
            new_name='image_record_id',
        ),
    ]
