# Generated by Django 2.0.6 on 2018-06-27 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0006_auto_20180626_2319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classified_at', models.DateTimeField(auto_now_add=True)),
                ('is_floor_plan', models.FloatField()),
            ],
            options={
                'ordering': ('classified_at',),
            },
        ),
        migrations.CreateModel(
            name='Classifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=512)),
                ('images', models.ManyToManyField(through='floor_plans.Classification', to='floor_plans.ImageRecord')),
            ],
        ),
        migrations.RemoveField(
            model_name='classifiedimage',
            name='image_record_id',
        ),
        migrations.DeleteModel(
            name='ClassifiedImage',
        ),
        migrations.AddField(
            model_name='classification',
            name='classifier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floor_plans.Classifier'),
        ),
        migrations.AddField(
            model_name='classification',
            name='image_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='floor_plans.ImageRecord'),
        ),
    ]
