# Generated by Django 2.0.6 on 2018-07-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0007_auto_20180628_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerecord',
            name='origin_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imagerecord',
            name='file',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
