# Generated by Django 2.0.6 on 2018-07-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floor_plans', '0008_auto_20180703_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='is_floor_plan',
            field=models.BooleanField(),
        ),
    ]
